Project my_blog {
    database_type: 'mysql'
}
Table users  as U {
    id int [pk, increment]
    username varchar [not null, unique]
    password text [not null]
    last_login timestamp [null]
    status boolean [default: true]
    created_at timestamp
    updated_at timestamp
}

Table role {
    id int [pk, increment]
    name string [not null, unique]
    created_at timestamp
    updated_at timestamp
}

Table user_role {
    id int [pk, increment]
    user_id int [not null]
    role_id int [not null]
    created_at timestamp
    updated_at timestamp
}

Table blog_category {
    id int [pk, increment]
    name varchar [not null]
    is_have_detail boolean [default: false]
    created_at timestamp
    updated_at timestamp
}

Table blog_detail_category {
    id int [pk, increment]
    name varchar [not null]
    blog_category_id int [not null]
    created_at timestamp
    updated_at timestamp
}

Table blog {
    id int [pk, increment]
    title varchar [not null]
    content longtext [not null]
    author int [not null]
    status boolean [default: true]
    category_id int [not null]
    detail_category_id int
    is_post boolean [default: false]
    is_main_blog boolean [default: false, note: 'blog who will be shown with the larger image']
    is_thumbnail_blog boolean [default: false, note: 'blog who will be shown with the smaller image']
    is_content_blog boolean [default: false, note: 'blog who will be shown with the starndart image size']
    created_at timestamp
    updated_at timestamp
}

Table blog_image {
    id int [pk, increment]
    path text [not null]
    blog_id int [not null]
}